name: Build UQM

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3


      - name: Initialize Emscripten
        uses: mymindstorm/setup-emsdk@v11

      - name: Verify Emscriptent is OK
        run: emcc -v

      - name: Download Emscripten ports
        run: emcc -c -E - -s USE_ZLIB=1 -s USE_LIBPNG=1 -s USE_VORBIS=1 -s USE_SDL=2 -s ASYNCIFY -pthread </dev/null

      - name: Build lipng
        run: |
          pushd .
          cd sc2/libpng-1.6.40
          emcmake cmake
          emmake make
          popd

      # Runs a set of commands using the runners shell
      - name: Build uqm
        run: |
          mkdir pub
          pushd .
          cd sc2
          emconfigure ./build.sh uqm config
          ./build.sh uqm
          popd
      - name: Publish files
        run: |
          cp sc2/src/emscripten/live.html ./index.html
          cp sc2/*.js ./
          cp sc2/*.wasm ./
          cp sc2/*.data ./
          rm -rf sc2
