name: Build UQM

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3


      - name: Initialize Emscripten
        uses: mymindstorm/setup-emsdk@v11

      - name: Verify Emscriptent is OK
        run: emcc -v

      - name: Download Emscripten ports
        run: emcc -c -E - -s USE_ZLIB=1 -s USE_LIBPNG=1 -s USE_VORBIS=1 -s USE_SDL=2 -s ASYNCIFY -pthread </dev/null

      # Runs a set of commands using the runners shell
      - name: Build uqm
        run: |
          pushd .
          cd sc2
          emconfigure ./build.sh uqm config
          ./build.sh uqm
          popd

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v3

      - name: Create site package
        run: |
          mkdir _site
          cp sc2/src/emscripten/live.html _site/
          cp sc2/uqm.js _site/
          cp sc2/uqm.worker.js _site/
          cp sc2/uqm.wasm _site/
          cp sc2/uqm.data _site/
          tar czvf github-pages _site

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v1


